name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

permissions:
  actions: read
  contents: read

env:
  DOCKER_NAMESPACE: kevinresol

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game:
          - abiotic-factor
          - project-zomboid
          - stationeers
          - valheim
          - satisfactory
          - space-engineers
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      # force build everything on code push
      - run: pnpm eval build-game-image --game=${{ matrix.game }} --force
        if: ${{ github.event_name != 'schedule' }}

      # build only updated games on schedule
      - run: pnpm eval build-game-image --game=${{ matrix.game }}
        if: ${{ github.event_name == 'schedule' }}
