name: Build

on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        game:
          - abiotic-factor
          - project-zomboid
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            pnpm eval build-game-image --game=${{ matrix.game }}
          else
            pnpm eval build-game-image --game=${{ matrix.game }} --force
          fi
