name: Don't Starve Together

on:
  push:
    branches:
      - master
    paths:
      - "./**"
      - "!games/**"
      - "games/dont-starve-together/**"

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./.github/workflows/template/push.yml
    secrets: inherit
    with:
      game: dont-starve-together
