name: Push

on:
  push:
    branches:
      - master
    paths:
      - "./**"
      - "!./games/**"
      - "games/project-zomboid/**"

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: ./push.yml
    with:
      game: project-zomboid
