name: Push

on:
  push:
    branches:
      - master
    paths:
      - "./**"
      - "!./games/**"
      - "games/stationeers/**"

permissions:
  actions: read
  contents: read

jobs:
  build:
    uses: .github/workflows/push.yml
    with:
      game: stationeers
